In [1]:
library(BSgenome.Hsapiens.UCSC.hg38)

Loading required package: BSgenome
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading required package: rtracklayer

#### Get the chromosome 1 sequence from hg38

In [2]:
chr1 <- Hsapiens[[1]]
chr1

  248956422-letter "DNAString" instance
seq: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

#### Load the L1 target site map data file, generated by map_genome.r

In [3]:
load('./data/large_files/chr1.rda')

In [4]:
ls()

[1] "chr1"    "chr1Map"

#### Each map holds 5 arrays in a list. The first, insites, contains positions in the sequence that are L1 target sites, the other four store which elements of insites are sites of each snap-velcro type (closed-tight, closed-loose, open-tight, open-loose). The first columns of the arrays contain target sites in the sense strand and the second contains those in the anti-sense strand

In [5]:
head(chr1Map[[1]])
head(chr1Map[[2]])
head(chr1Map[[3]])
head(chr1Map[[4]])
head(chr1Map[[5]])

     insites_s insites_ns
[1,] 11034     10247
[2,] 11265     10248
[3,] 11321     10254
[4,] 11382     10255
[5,] 11444     10513
[6,] 11468     10543

     ict_s ict_ns
[1,]  44    29
[2,]  45    32
[3,]  46    33
[4,]  70    34
[5,] 406   219
[6,] 421   321

     icl_s icl_ns
[1,] 29     19
[2,] 32    110
[3,] 33    139
[4,] 43    148
[5,] 51    158
[6,] 64    159

     iot_s iot_ns
[1,]  8     28
[2,] 15     30
[3,] 17     31
[4,] 28     35
[5,] 30     36
[6,] 31    108

     iol_s iol_ns
[1,] 1     1
[2,] 2     2
[3,] 3     3
[4,] 4     4
[5,] 5     5
[6,] 6     6

#### Here we can print the snap and velcro sections of any site to verify that the map is precise. Sense sites have snap and velcro regions before them in the 5' direction. Anti-sense sites have snap and velcro regions ahead of them in the 3' direction

In [6]:
site <- chr1Map$insites[chr1Map$icl[5,1],1] # Sense if column indices are 1, anti-sense if 2, both should be same
chr1[(site-9):site] # Print sense site snap/velcro
# chr1[site:(site+9)] # Print anti-sense site snap/velcro

  10-letter "DNAString" instance
seq: TGATGATTTT

#### The function map_sequence() will perform the mapping for any DNAString object

In [1]:
source('./map_sequence.r')

In [2]:
test <- DNAString(c('CCCCTTCTCAACAACCTTCTCTATGTTTTGTACGCGATGGTAAAGACGTCGAG'))
testMap <- map_sequence(test)

ERROR: Error in DNAString(c("CCCCTTCTCAACAACCTTCTCTATGTTTTGTACGCGATGGTAAAGACGTCGAG")): could not find function "DNAString"

In [9]:
testMap

$insites
     insites_s insites_ns
[1,]         8         10
[2,]        20         11
[3,]        27         41
[4,]        28         42
[5,]        29         43
[6,]        30         NA
[7,]        31         NA

$ict
     ict_s ict_ns

$icl
     icl_s icl_ns
[1,]     5     NA

$iot
     iot_s iot_ns
[1,]     4     NA
[2,]     6     NA
[3,]     7     NA

$iol
     iol_s iol_ns
[1,]     1      1
[2,]     2      2
[3,]     3      3
[4,]    NA      4
[5,]    NA      5

In [10]:
site <- testMap$insites[testMap$iot[1,1],1]
test[(site-9):site]
# test[site:(site+9)]

  10-letter "DNAString" instance
seq: CTCTATGTTT